### ISSUE TITLE
Changes not displaying

### ISSUE THREAD

**Issue by SamMorgan** [krjo/shopify-webpack-dev-workflow#1]
I can see the changes on the bundle files in dist/assets but they don't seem to be coming though to the applications files. Am I missing a step?

**Comment by krjo** [comment]
I just updated the readme today when I realized that theme kit was overwriting the `config.yml` file when you create a new theme. Make sure your `config.yml` file looks like this:

```
development:
  password: <PRIVATE_APP_PASSWORD>
  theme_id: "<THEME_ID>"
  store: <STORE_URL>
  directory: dist/
  ignore_files:
    - config/settings_data.json
```
